title: NeurotrackApp Wiki
description: Documentação completa do NeurotrackApp - Organizando o caos com inteligência e empatia
baseurl: ""
url: ""
theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Configurações de coleções para organizar o conteúdo
collections:
  casos-uso:
    output: true
    permalink: /:collection/:path/
  arquitetura:
    output: true
    permalink: /:collection/:path/
  api:
    output: true
    permalink: /:collection/:path/
  codigo:
    output: true
    permalink: /:collection/:path/

# Configurações de navegação
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "casos-uso"
    values:
      sidebar: casos-uso-sidebar
  - scope:
      path: "arquitetura"
    values:
      sidebar: arquitetura-sidebar
  - scope:
      path: "api"
    values:
      sidebar: api-sidebar
  - scope:
      path: "codigo"
    values:
      sidebar: codigo-sidebar

# Excluir arquivos e diretórios do processamento
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
